services:
  - type: web
    name: bendine-backend
    env: python
    region: oregon
    build_command: pip install -r requirements.txt
    start_command: uvicorn main:app --host 0.0.0.0 --port $PORT
    env_vars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: YOUR_DATABASE_URL
      - key: SUPABASE_URL
        value: YOUR_SUPABASE_URL
      - key: SUPABASE_KEY
        value: YOUR_SUPABASE_KEY
      - key: SECRET_KEY
        value: YOUR_SECRET_KEY
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440